/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>
#include <string>

#pragma once
using namespace std;
#ifdef __cplusplus
extern "C" {
#endif
JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM *jvm, void *reserved);
/*
 * Class:     com_example_testedit_PythonThread
 * Method:    initPython
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_testedit_PythonThread_initPython
        (JNIEnv *, jobject, jstring aPath);

/*
 * Class:     com_example_testedit_PythonThread
 * Method:    cleanupPython
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_testedit_PythonThread_cleanupPython
        (JNIEnv *, jobject);

/*
 * Class:     com_example_testedit_PythonThread
 * Method:    runPython
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_testedit_PythonThread_runPython
        (JNIEnv *, jobject, jstring filename);

JNIEXPORT jstring JNICALL returnPython(JNIEnv* env, jobject obj,string message);
#ifdef __cplusplus
}
#endif


