/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>
#include <string>

#pragma once
using namespace std;
#ifdef __cplusplus

extern "C" {
#endif

class JNI_obj {


public:
    jobject obj;
    JNIEnv *env;
public:
    JNI_obj() {

    };
public:
    JNI_obj(JNIEnv *env, jobject obj) {
        this->env = env;
        this->obj = obj;
    };

};
class PyLogs {
public:
    void LOG(string message);
};

JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM *jvm, void *reserved);
/*
 * Class:     com_example_testedit_pythonInpreter_PythonThread_
 * Method:    initPython
 * Signature: ()I
 */

JNIEXPORT jint JNICALL Java_com_example_testedit_pythonInpreter_PythonThread_initPython
        (JNIEnv *, jobject, jstring aPath);

/*
 * Class:     com_example_testedit_pythonInpreter_PythonThread_
 * Method:    cleanupPython
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_testedit_pythonInpreter_PythonThread_cleanupPython
        (JNIEnv *, jobject);

/*
 * Class:     com_example_testedit_pythonInpreter_PythonThread_
 * Method:    runPython
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_testedit_pythonInpreter_PythonThread_runPython
        (JNIEnv *, jobject, jstring filename);

/*
 * Class:     com_example_testedit_pythonInpreter_PythonThread_
 * Method:    returnInfoPython
 * Signature: ()I
 */

JNIEXPORT void JNICALL Java_com_example_testedit_pythonInpreter_PythonReturn_returnInfoPython
        (JNIEnv *env, jobject obj);

/*
 * Class:     com_example_testedit_pythonInpreter_PythonThread_
 * Method:    returnPython
 * Signature: ()I
 */

JNIEXPORT void JNICALL returnPython(JNIEnv *env, jobject obj, string message);

/*
 * Class:     com_example_testedit_pythonInpreter_PythonThread_
 * Method:    getStatusPy
 * Signature: ()I
 */

JNIEXPORT jboolean JNICALL
Java_com_example_testedit_pythonInpreter_PythonReturn_getStatusPy(JNIEnv *env, jobject thiz);

/*
 * Class:     com_example_testedit_pythonInpreter_PythonThread_
 * Method:    getStatusResult
 * Signature: ()I
 */

JNIEXPORT jboolean JNICALL
Java_com_example_testedit_pythonInpreter_PythonReturn_getStatusResult(JNIEnv *env, jobject thiz);

/*
 * Class:     com_example_testedit_pythonInpreter_PythonThread_
 * Method:    getStatusError
 * Signature: ()I
 */

JNIEXPORT jboolean JNICALL
Java_com_example_testedit_pythonInpreter_PythonReturn_getStatusError(JNIEnv *env, jobject thiz);

/*
 * Class:     com_example_testedit_pythonInpreter_PythonThread_
 * Method:    getStatusErrorResult
 * Signature: ()I
 */

JNIEXPORT jboolean JNICALL
Java_com_example_testedit_pythonInpreter_PythonReturn_getStatusErrorResult(JNIEnv *env,
                                                                           jobject thiz);

/*
 * Class:     com_example_testedit_pythonInpreter_PythonThread_
 * Method:    getResult
 * Signature: ()I
 */

JNIEXPORT jstring JNICALL
Java_com_example_testedit_pythonInpreter_PythonReturn_getResult(JNIEnv *env, jobject thiz);

/*
 * Class:     com_example_testedit_pythonInpreter_PythonThread_
 * Method:    getError
 * Signature: ()I
 */

JNIEXPORT jstring JNICALL
Java_com_example_testedit_pythonInpreter_PythonReturn_getError(JNIEnv *env, jobject thiz);


#ifdef __cplusplus
}

#endif


